name: Build and Deploy to GitHub Pages
on:
  push:
    branches:
      - main  # або інша гілка, з якої ви хочете робити деплой

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run generate

    - name: Configure Git
      run: |
        git config --global user.email "anyavlasenko@gmail.com"
        git config --global user.name "Anna Komarova"

    - name: Check if gh-pages exists
      run: |
        if [ $(git branch --list gh-pages) ]; then
          echo "gh-pages exists."
        else
          git checkout --orphan gh-pages
          git reset --hard
          git commit --allow-empty -m "Initialize gh-pages branch"
          git push origin gh-pages
          git checkout main
        fi

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output/public
